### ISSUE TITLE
observe_pulsar longitude parameter?

### ISSUE THREAD

**Issue by 0xCoto** [ccera-astro/pulsar_filterbank#1]
Hi there,

I've managed to install everything according to the .doc, but I'm having a hard time understanding how the longitude parameter (`-74.4057` in this case) works. As far as I understand, it's there to automatically begin the observation when the source rises above the horizon? What's weird is that regardless of what longitude I set, it never seems to begin acquiring data immediately. Why is that? Is there a way to begin observing immediately without checking if the pulsar is above the horizon (just for testing purposes)?

> apostolos@sdr5:~/pulsar_filterbank$ observe_pulsar b0329+54 1410 1 73 1 -74.4057
Found type=b200,num_recv_frames=128,master_clock_rate=4000000.0,subdev='A:A' running at 1000000.0 on 1410000000.0
Will run for 60 seconds
PSR params: PW50 0.006600 DM 26.76 RA 3.542 DEC 54.576
Waiting for pulsar to rise at: 3.53345299145, current LMST is 5.625278
Waiting for pulsar to rise at: 3.53345299145, current LMST is 5.629444
Waiting for pulsar to rise at: 3.53345299145, current LMST is 5.633611
Waiting for pulsar to rise at: 3.53345299145, current LMST is 5.637778

Thanks in advance!

EDIT: Trying to use a USRP B210 at 1410 MHz with 1 MHz bandwidth with a gain of 73 dB and observing duration of 1 minute (in case that matters)

**Comment by ccera-astro** [comment]
The 'observe_pulsar' application is just a script that wraps around the underlying Gnu Radio flow-graph, which you can always use directly.  I'll consider adding some kind of "do this immediately"  option to 'observe_pulsar'.  The script also assumes that your system clock is set correctly, otherwise, it cannot make a correct determination of your LMST.  I'll also comment that a 1-minute observing run on any pulsar for an amateur instrument is going to produce a worthless observation.  But for testing, sure.

**Comment by ccera-astro** [comment]
Fixed in commit 59238d3d7ae324dd275b67403122164f72074a79
